# Generated by Django 2.2.19 on 2021-05-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.CharField(max_length=255)),
                ('output_text', models.CharField(max_length=255)),
                ('pos_tags', models.CharField(blank=True, max_length=255, null=True)),
                ('tagging', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'conversation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Userinput',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('userinput', models.CharField(blank=True, db_column='userInput', max_length=255, null=True)),
            ],
            options={
                'db_table': 'userInput',
                'managed': False,
            },
        ),
    ]
